### ISSUE TITLE
fix: Configuration loader is throwing error

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#177]
**Describe the bug**
The version 0.2.5 can read multiple configuration files. But if  

**Expected behavior**
The configuration files can have either `data_sources` or `metrics`. Both are not optional. `data_sources` can be present in any of the file in a directory. 

**To Reproduce**
Add multiple configuration files and add only metrics in one file without data_sources key.

**Screenshots**
<img width="1714" alt="Screenshot 2024-01-15 at 5 18 00 PM" src="https://github.com/waterdipai/datachecks/assets/2178361/d60a6f1a-d826-4c47-8b48-e33563db8ce7">

**Logs and additional context**
```
{"@timestamp": "2024-01-15T10:09:32.785Z", "level": "ERROR", "projectName": "ecommerce-search-dqm", "message": "failed to run datachecks: 'data_sources'", "thread": "MainThread", "logger_name": "__main__", "pro │
│ Traceback (most recent call last):                                                                                                                                                                                 │
│   File "/src/jobs.py", line 23, in wrapper                                                                                                                                                                         │
│     return job_func(*args, **kwargs)                                                                                                                                                                               │
│   File "/src/jobs.py", line 36, in job                                                                                                                                                                             │
│     run_datachecks_with_config(tenant=tenant_name)                                                                                                                                                                 │
│   File "/src/app/run.py", line 26, in run_datachecks_with_config                                                                                                                                                   │
│     inspector = Inspect(configuration=load_configuration(config_path))                                                                                                                                             │
│   File "/usr/local/lib/python3.10/site-packages/datachecks/core/configuration/configuration_parser.py", line 370, in load_configuration                                                                            │
│     final_config_dict["data_sources"].extend(config_dict["data_sources"])                                                                                                                                          │
│ KeyError: 'data_sources'
```

**Comment by datageek00** [comment]
fixed with #181
